---
binary_sensor:
  - platform: template
    sensors:
      someone_home:
        unique_id: someone_home
        friendly_name: Someone home
        value_template: >-
          {{ is_state('person.tor', 'home')
              or is_state('input_boolean.guest_mode', 'on') }}
        icon_template: >-
          {% if is_state('person.tor', 'home')
              or is_state('input_boolean.guest_mode', 'on') %}
            mdi:home-account
          {% else %}
            mdi:home
          {% endif %}
      tv_active:
        unique_id: tv_active
        friendly_name: TV Active
        value_template: >-
          {{ states('sensor.tv_outlet_power') |
          int > 30 or states('media_player.plex_tv') != 'unavailable'
          }}
      kitchen_extractor_fan:
        unique_id: kitchen_extractor_fan
        friendly_name: Kitchen extractor fan
        value_template: >-
          {{ states('sensor.extractor_fan_outlet_power') | int > 30 }}
        icon_template: >-
          {% if states('sensor.extractor_fan_outlet_power') | int > 30 %}
            mdi:fan
          {% else %}
            mdi:fan-off
          {% endif %}
