---
extends: default

ignore: |
  automations.yaml
  blueprints/
  custom_components
  secrets.yaml
  scenes.yaml
  zigbee2mqtt
  scripts.yaml
  themes/
  .esphome/
  notebooks/bokeh-examples
  notebooks/home-assistant
