- platform: template
  sensors:
    someone_home:
      unique_id: someone_home
      friendly_name: Someone home
      value_template: >-
        {{ is_state('person.tor', 'home')
            or is_state('input_boolean.guest_mode', 'on') }}
      icon_template: >-
        {% if is_state("binary_sensor.someone_home", "on") %}
          mdi:home-account
        {% else %}
          mdi:home
        {% endif %}
