
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# TODO: find out what I actually care about
recorder:
  exclude:
    domains:
      - sensor
      - binary_sensor
  include:
    entity_globs:
      - sensor.*_action
      - binary_sensor.*_occupancy

automation manual: !include_dir_merge_list automations
automation ui: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml
