---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  packages: !include_dir_named integrations
  allowlist_external_dirs:
    - /tmp

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
