---

default_config:

logger:
  default: warning
  logs:
    custom_components.pyscript: info

tts:
  - platform: google_translate

# TODO: find out what I actually care about
recorder:
  exclude:
    entity_globs:
      - sensor.*linkquality
      - sensor.*update*
      - sensor.*requested_brightness*
      - sensor.*battery
      - sensor.*motion_illuminance*
      - sensor.*power_on_behavior

input_boolean: !include helpers/input_booleans.yaml
input_datetime: !include helpers/input_datetimes.yaml
input_number: !include helpers/input_numbers.yaml
input_text: !include helpers/input_texts.yaml

automation manual: !include_dir_merge_list automations
automation ui: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include sensors/sensors.yaml

adaptive_lighting: !include integrations/adaptive_lighting.yaml
spotcast: !include integrations/spotcast.yaml
spotify: !include integrations/spotify.yaml
device_tracker: !include integrations/device_tracker.yaml
octoprint: !include integrations/octoprint.yaml
ios: !include integrations/ios.yaml
pyscript: !include pyscript/config.yaml
