default_config:

# Text to speech
tts:
  - platform: google_translate

# TODO: find out what I actually care about
recorder:
  exclude:
    entity_globs:
      - sensor.*linkquality
      - sensor.*update*
      - sensor.*requested_brightness*
      - sensor.*battery
      - sensor.*motion_illuminance*
      - sensor.*power_on_behavior

input_boolean: !include inputs/input_booleans.yaml

automation manual: !include_dir_merge_list automations
automation ui: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml
binary_sensor: !include binary_sensors.yaml

adaptive_lighting: !include integrations/adaptive_lighting.yaml
spotcast: !include integrations/spotcast.yaml
spotify: !include integrations/spotify.yaml
device_tracker: !include integrations/device_tracker.yaml
