---
- id: 1e9d43ee-b793-44d5-98ed-6f8bf24bc3a2
  alias: "Bedroom: Light switch"
  use_blueprint:
    path: z2m_aqara_opple.yaml
    input:
      remote: sensor.bedroom_switch_action
      button_1_single:
        - service: light.turn_off
          target:
            entity_id: light.bedroom_ceiling
      button_2_single:
        - service: light.turn_on
          target:
            entity_id: light.bedroom_ceiling
      button_3_single:
        - service: light.turn_off
          target:
            entity_id: light.bed_reading_light
      button_4_single:
        - service: light.turn_on
          target:
            entity_id: light.bed_reading_light

- alias: "Light: turn off bedroom lights after 2 hours"
  id: 05ba2406-7b7c-44fb-a70c-a72f8c549e52
  trigger:
    platform: state
    entity_id: light.bedroom_ceiling
    from: "off"
    to: "on"
    for:
      hours: 2
  action:
    - service: light.turn_off
      target:
        entity_id: light.bedroom_ceiling
