---
- alias: "3D printer: send notification when done"
  id: a1f21b60-4e75-42dd-b32f-a24cbdf54129
  trigger:
    - platform: state
      entity_id: binary_sensor.ender_3_pro_printing
      from: 'on'
      to: 'off'
  action:
    - service: notify.mobile_app_tors_iphone
      data:
        message: '3D print is done'
