- alias: Coffe maker button turns outlet on/off
  id: coffee_maker_button_turns_outlet_on_off
  use_blueprint:
    path: simple_on_off.yaml
    input:
      trigger_entity: sensor.coffee_maker_button_action
      target_entity:
        entity_id: switch.coffee_maker_outlet
