- alias: Entrance light controlled by motion sensor
  use_blueprint:
    path: simple_on_off.yaml
    input:
      trigger_entity: binary_sensor.entrance_motion_sensor_occupancy
      target_entity:
        entity_id: light.entrance
