---
- alias: "Guest mode: disable automations"
  id: 7d1a9ce5-cd62-440e-ac9a-a46cc0777395
  trigger:
    - platform: state
      entity_id: input_boolean.guest_mode
  action:
    service: >
      {% if trigger.to_state.state == "on" %}
        automation.turn_off
      {% else %}
        automation.turn_on
      {% endif %}
    target:
      entity_id: group.automations_to_disable_in_guest_mode
