---
- alias: "Leaving: Turn off everything when nobody is home"
  id: 7a80a995-94c3-494d-9840-cc01ce50b268
  mode: restart
  trigger:
    platform: state
    entity_id: binary_sensor.someone_home
    to: "off"
  action:
    service: script.turn_off_everything

- alias: "Leaving: Ask to turn off everything when guest mode is on"
  id: 28b233ce-ea65-413c-abfc-0a212eca7545
  mode: restart
  max_exceeded: silent
  trigger:
    platform: state
    entity_id: person.tor
    from: "home"
    to: "away"
  condition:
    - condition: state
      state: "on"
      entity_id: input_boolean.guest_mode
  action:
    - alias: "Set up variables for the actions"
      variables:
        action_everything: "{{ 'TURN_OFF_EVERYTHING_' ~ context.id }}"
        action_guest_mode: "{{ 'TURN_OFF_GUEST_MODE_' ~ context.id }}"
        action_dismiss: "{{ 'DISMISS_' ~ context.id }}"
    - service: notify.mobile_app_tors_iphone
      data:
        message: Something happened at home!
        data:
          actions:
            - action: "{{ action_everything }}"
              title: Turn off everything
            - action: "{{ action_guest_mode }}"
              title: Turn off guest mode
            - action: "{{ action_dismiss }}"
              title: Dismiss
    - alias: Wait for response
      wait_for_trigger:
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: "{{ action_everything }}"
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: "{{ action_guest_mode }}"
        - platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: "{{ action_dismiss }}"
    - alias: Perform the action
      choose:
        - conditions: >
            "{{ wait.trigger.event.data.action == action_everything }}"
          sequence:
            service: script.turn_off_everything
        - conditions: >
            "{{ wait.trigger.event.data.action == action_guest_mode }}"
          sequence:
            service: input_boolean.turn_off
            target:
              entity_id: input_boolean.guest_mode
