---
- alias: "Leaving: Turn off everything when nobody is home"
  id: 7a80a995-94c3-494d-9840-cc01ce50b268
  trigger:
    platform: state
    entity_id: binary_sensor.someone_home
    to: "off"
  action:
    service: script.turn_off_everything

- alias: "Leaving: Ask to turn off everything when leaving and guest mode is on"
  id: e69cb7f5-e479-465e-9472-37d11a4d8113
  trigger:
    platform: state
    entity_id: person.tor
    from: "home"
  condition:
    condition: state
    entity_id: input_boolean.guest_mode
    state: "on"
  action:
    service: notify.mobile_app_tors_iphone
    data:
      message: Guest mode is on. Turn everything off?
      data:
        push:
          category: TURN_OFF_GUEST_MODE_OR_EVERYTHING

- alias: "Leaving: Turn off everything on notification action"
  id: 0d9897b4-73b9-4125-920f-1069a49d6f88
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      categoryName: TURN_OFF_GUEST_MODE_OR_EVERYTHING
      actionName: TURN_OFF_EVERYTHING
  action:
    service: script.turn_off_everything

- alias: "Leaving: Turn off guest mode on notification action"
  id: 545ac4ad-3d83-4444-b9b6-e6e1873a6a3f
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      categoryName: TURN_OFF_GUEST_MODE_OR_EVERYTHING
      actionName: TURN_OFF_GUEST_MODE
  action:
    service: input_boolean.turn_off
    target:
      entity_id: input_boolean.guest_mode
