# TODO: Move to pyscript and take door sensor into account
- alias: Bathroom motion sensor turns light on/off
  id: bathroom_motion_sensor_turns_light_on_off
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: '420' # Trådfri sensor, 3 min + 420 sec = 10 min
      motion_entity: binary_sensor.bathroom_motion_occupancy
      light_target:
        entity_id: light.bathroom_ceiling

- alias: Entrance motion sensor turns light on/off
  id: entrance_motion_sensor_turns_light_on_off
  use_blueprint:
    path: simple_on_off.yaml
    input:
      trigger_entity: binary_sensor.entrance_motion_sensor_occupancy
      target_entity:
        entity_id: light.entrance

- alias: Storage room door sensor turns light on/off
  id: storage_room_door_sensor_turns_light_on_off
  use_blueprint:
    path: simple_on_off.yaml
    input:
      trigger_entity: binary_sensor.storage_room_door_contact
      target_entity:
        entity_id: light.storage_room

- alias: Turn on living room lights when someone comes home
  id: turn_on_living_room_lights_when_someone_comes_home
  trigger:
    - platform: state
      entity_id: binary_sensor.someone_home
      from: 'off'
      to: 'on'
  condition:
    - condition: sun
      after: sunset
      after_offset: -00:30:00
  action:
    - service: light.turn_on
      entity_id: light.living_room_ceiling

- alias: Turn on living room lights before sunset
  id: turn_on_living_room_lights_before_sunset
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:30:00'
  condition:
    - condition: state
      entity_id: binary_sensor.someone_home
      state:  'on' 
    - condition: state
      entity_id: light.living_room_ceiling
      state:  'off' 
    - condition: state
      entity_id: input_boolean.night_mode
      state:  'off' 
  action:
    - service: light.turn_on
      entity_id: light.living_room_ceiling

- alias: Reading chair presence turns reading lamp on/off
  id: reading_chair_presence_turns_reading_lamp_on_off
  use_blueprint:
    path: simple_on_off.yaml
    input:
      # state is flipped. Presence sensor is an aqara contact sensor wired to a pressure sensor
      turn_off_state: 'on'
      turn_on_state: 'off'
      trigger_entity: binary_sensor.reading_chair_presence_contact
      target_entity:
        entity_id: light.reading_lamp

- alias: Ansluta remote toggles kitchen lights
  id: ansluta_remote_toggles_kitchen_lights
  trigger:
    - platform: event
      event_type: esphome.ansluta_remote_clicked
      event_data:
        address: 35c0
  action:
    - service: light.toggle
      target:
        entity_id: light.kitchen
  mode: single

- alias: Bedroom motion sensor turns bedroom lights on/off
  id: bedroom_motion_sensor_turns_lights_on_off
  # TODO: would be nice to be able to override this.
  # Keep the lights on if light was turned on manually or by the Hue remote
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.bedroom_motion_occupancy
      light_target:
        entity_id: light.bedroom_ceiling