# TODO: Move to pyscript and take door sensor into account
- alias: Bathroom light controlled by motion sensor
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: '420' # Trådfri sensor, 3 min + 420 sec = 10 min
      motion_entity: binary_sensor.bathroom_motion_occupancy
      light_target:
        entity_id: light.bathroom_ceiling

- alias: Entrance light controlled by motion sensor
  use_blueprint:
    path: simple_on_off.yaml
    input:
      trigger_entity: binary_sensor.entrance_motion_sensor_occupancy
      target_entity:
        entity_id: light.entrance

- alias: Storage room light controlled by door sensor
  use_blueprint:
    path: simple_on_off.yaml
    input:
      trigger_entity: binary_sensor.storage_room_door_contact
      target_entity:
        entity_id: light.storage_room

- alias: Turn on living room lights when someone comes home
  trigger:
    - platform: state
      entity_id: binary_sensor.someone_home
      from: 'off'
      to: 'on'
  condition:
    - condition: sun
      after: sunset
      after_offset: -00:30:00
  action:
    - service: light.turn_on
      entity_id: light.living_room_ceiling