---
# TODO: Use monitoring plug to check TV status
- alias: "Media: Turn on receiver when TV is used"
  trigger:
    - platform: state
      entity_id: media_player.tv
      from: "off"
      to: "on"
    - platform: state
      entity_id: media_player.plex_tv
      to: "playing"
  action:
    - service: media_player.turn_on
      entity_id: media_player.living_room_receiver
    - service: media_player.select_source
      entity_id: media_player.living_room_receiver
      data:
        source: optical
