---
- alias: "Media: Turn on receiver when TV is used"
  trigger:
    - platform: state
      entity_id: binary_sensor.tv_active
      from: "off"
      to: "on"
  action:
    - service: media_player.turn_on
      entity_id: media_player.living_room_receiver
    - service: media_player.select_source
      entity_id: media_player.living_room_receiver
      data:
        source: optical
