---
- alias: "Night mode: Night mode turns adaptive lighting sleep mode on/off"
  id: 57e44684-312e-4e7c-a637-0a3b7638f1af
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
  action:
    - service: switch.turn_{{ trigger.to_state.state }}
      data:
        entity_id: switch.adaptive_lighting_sleep_mode_default

- alias: 'Night mode: Turn off lights 2 minutes after night mode turned on'
  id: ea11370d-304a-4b75-b573-658885354e66
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'on'
      for: 00:02:00
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: light.turn_off
      entity_id:
        - light.bedroom_ceiling
        - light.kitchen
        - light.living_room_ceiling
        - light.reading_lamp
        - light.desk_lamp

- alias: "Night mode: Turn off night mode at 06:00"
  id: 4f1bd80a-81ea-4e80-828d-5948b80b66f1
  trigger:
    - platform: time
      at: '06:00:00'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.night_mode
