---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  workflow_dispatch:

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run yamllint
        run: |
          yamllint --strict .

  pyscript-flake8:
    name: Lint pyscript scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install flake8
        run: python -m pip install flake8
      - name: Lint with flake8
        run: |
          cd pyscript
          flake8
