---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  workflow_dispatch:

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run yamllint
        run: |
          yamllint --strict .
